### ISSUE TITLE
Is it possible to install a package from GIT repository?

### ISSUE THREAD

**Issue by SeanWong24** [pyodide/micropip#77]
Like what pip does using this ```pip install git+https://repository.url@tag```.

**Comment by ryanking13** [comment]
No, it is not possible.

Unlike pip, micropip only supports installing a prebuilt wheel, and it does not build packages from source. So installing a package from git repository (== building from source) is not possible.

**Comment by m-aciek** [comment]
Could the error message be improved? Would you accept a PR for it?

Current experience:
```python
>>> await install('git+https://forge.apps.education.fr/basthon/basthon-kernel#subdirectory=packages/kernel-python3/src/modules/turtle')
Traceback (most recent call last):
  File "/lib/python3.13/site-packages/micropip/_vendored/packaging/src/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/lib/python3.13/site-packages/micropip/_vendored/packaging/src/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/lib/python3.13/site-packages/micropip/_vendored/packaging/src/packaging/_parser.py", line 124, in _parse_requirement_details
    marker = _parse_requirement_marker(
        tokenizer,
    ...<5 lines>...
        ),
    )
  File "/lib/python3.13/site-packages/micropip/_vendored/packaging/src/packaging/_parser.py", line 145, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        f"Expected end or semicolon (after {after})",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        span_start=span_start,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/lib/python3.13/site-packages/micropip/_vendored/packaging/src/packaging/_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
    ...<3 lines>...
    )
micropip._vendored.packaging.src.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    git+https://forge.apps.education.fr/basthon/basthon-kernel#subdirectory=packages/kernel-python3/src/modules/turtle
       ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.13/site-packages/micropip/package_manager.py", line 205, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.13/site-packages/micropip/transaction.py", line 74, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.13/site-packages/micropip/transaction.py", line 81, in add_requirement
    as_req = constrain_requirement(Requirement(req), self.constrained_reqs)
                                   ~~~~~~~~~~~^^^^^
  File "/lib/python3.13/site-packages/micropip/_vendored/packaging/src/packaging/requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
micropip._vendored.packaging.src.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    git+https://forge.apps.education.fr/basthon/basthon-kernel#subdirectory=packages/kernel-python3/src/modules/turtle
       ^
```

**Comment by ryanking13** [comment]
> Could the error message be improved? Would you accept a PR for it?

Sure, PR welcome
